import random

LETTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
NUMBERS = "0123456789"
SYMBOLS = "!#$%^&()*+"

def generate(nr_letters, nr_symbols, nr_numbers):
  password = []
  for i in range(nr_letters):
    password.append(random.choice(LETTERS))
  for i in range(nr_symbols):
    password.append(random.choice(SYMBOLS))
  for i in range(nr_numbers):
    password.append(random.choice(NUMBERS))

  random.shuffle(password)
  return ''.join(password)


def main():
  print("Welcome to the PyPassword Generator!")
  nr_letters= int(input("How many letters would you like in your password?\n")) 
  nr_symbols = int(input(f"How many symbols would you like?\n"))
  nr_numbers = int(input(f"How many numbers would you like?\n"))

  password = generate(nr_letters, nr_symbols, nr_numbers)

  print(f"Your autogenerated password is: {password}")

if __name__ =='__main__':
  main()
